"""Storage protocol used by both SQLite (local/demo) and Supabase (production)."""
from __future__ import annotations

from typing import Any, Protocol


class Store(Protocol):
    backend_name: str

    def create_session(self, data: dict[str, Any]) -> None: ...
    def get_session(self, session_id: str) -> dict[str, Any] | None: ...
    def get_history(self, user_email: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def delete_sessions(self, user_email: str) -> None: ...

    def save_quiz_result(self, data: dict[str, Any]) -> None: ...
    def get_quiz_history(self, user_email: str, limit: int = 20) -> list[dict[str, Any]]: ...
    def list_quiz_results(self, user_email: str) -> list[dict[str, Any]]: ...
    def delete_quiz_results(self, user_email: str) -> None: ...
    def list_session_dates(self, user_email: str, limit: int = 100) -> list[str]: ...
    def count_sessions(self, user_email: str) -> int: ...

    def get_concept_mastery(self, user_email: str, concept: str) -> dict[str, Any] | None: ...
    def upsert_concept_mastery(self, data: dict[str, Any], existing_id: str | None) -> None: ...
    def list_concept_mastery(self, user_email: str) -> list[dict[str, Any]]: ...
    def delete_mastery(self, user_email: str) -> None: ...

    def create_document(self, data: dict[str, Any]) -> None: ...
    def get_document(self, document_id: str) -> dict[str, Any] | None: ...
    def list_documents(self, user_email: str) -> list[dict[str, Any]]: ...
    def update_document(self, document_id: str, fields: dict[str, Any]) -> None: ...
    def delete_document(self, document_id: str) -> None: ...

    def replace_chunks(self, document_id: str, chunks: list[dict[str, Any]]) -> None: ...
    def list_chunks_for_user(self, user_email: str, document_ids: list[str] | None = None) -> list[dict[str, Any]]: ...
    def delete_chunks(self, document_id: str) -> None: ...

    def upsert_kg_concept(self, data: dict[str, Any]) -> None: ...
    def list_kg_concepts(self) -> list[dict[str, Any]]: ...
    def upsert_kg_relationship(self, data: dict[str, Any]) -> None: ...
    def list_kg_relationships(self) -> list[dict[str, Any]]: ...

    def log_event(self, data: dict[str, Any]) -> None: ...
    def list_events(self, user_email: str | None, limit: int = 50) -> list[dict[str, Any]]: ...

    def save_prediction(self, data: dict[str, Any]) -> None: ...
    def list_predictions(self, user_email: str) -> list[dict[str, Any]]: ...
