"""Seed a real ML-focused knowledge graph used for prerequisites and recommendations."""
from __future__ import annotations

CONCEPTS = [
    ("machine-learning", "Machine Learning", "ml", "Systems that improve from data rather than explicit rules.", 0.35),
    ("supervised-learning", "Supervised Learning", "ml", "Learning a mapping from labeled examples.", 0.4),
    ("unsupervised-learning", "Unsupervised Learning", "ml", "Finding structure in unlabeled data.", 0.45),
    ("classification", "Classification", "ml", "Predicting discrete labels.", 0.45),
    ("regression", "Regression", "ml", "Predicting continuous values.", 0.45),
    ("logistic-regression", "Logistic Regression", "ml", "Linear model for classification using a logistic function.", 0.55),
    ("linear-regression", "Linear Regression", "ml", "Linear model for continuous targets.", 0.5),
    ("model-evaluation", "Model Evaluation", "ml", "Measuring how well a model generalizes.", 0.5),
    ("precision", "Precision", "ml", "Of predicted positives, how many are actually positive.", 0.55),
    ("recall", "Recall", "ml", "Of actual positives, how many were found.", 0.55),
    ("f1-score", "F1 Score", "ml", "Harmonic mean of precision and recall.", 0.6),
    ("confusion-matrix", "Confusion Matrix", "ml", "Table of predicted vs actual class counts.", 0.5),
    ("overfitting", "Overfitting", "ml", "Fitting training noise so generalization suffers.", 0.5),
    ("underfitting", "Underfitting", "ml", "Model too simple to capture the signal.", 0.45),
    ("bias-variance", "Bias-Variance Tradeoff", "ml", "Balance between underfitting and overfitting.", 0.65),
    ("train-test-split", "Train/Test Split", "ml", "Holding out data to estimate generalization.", 0.4),
    ("cross-validation", "Cross-Validation", "ml", "Repeated held-out evaluation on folds.", 0.55),
    ("feature-engineering", "Feature Engineering", "ml", "Transforming raw inputs into useful features.", 0.5),
    ("regularization", "Regularization", "ml", "Penalizing complexity to reduce overfitting.", 0.6),
    ("gradient-descent", "Gradient Descent", "ml", "Iterative optimizer following the negative gradient.", 0.6),
    ("neural-networks", "Neural Networks", "ml", "Layered function approximators trained by backprop.", 0.7),
    ("decision-trees", "Decision Trees", "ml", "Axis-aligned recursive partitions of the feature space.", 0.5),
    ("random-forest", "Random Forest", "ml", "Bagged ensemble of decision trees.", 0.6),
    ("probability", "Probability", "foundations", "Quantifying uncertainty of events.", 0.35),
    ("linear-algebra", "Linear Algebra", "foundations", "Vectors, matrices, and linear maps.", 0.4),
    ("calculus", "Calculus", "foundations", "Derivatives and rates of change used in optimization.", 0.45),
]

# relation: prerequisite means source is required before target
RELATIONSHIPS = [
    ("machine-learning", "supervised-learning", "includes"),
    ("machine-learning", "unsupervised-learning", "includes"),
    ("supervised-learning", "classification", "includes"),
    ("supervised-learning", "regression", "includes"),
    ("classification", "logistic-regression", "includes"),
    ("regression", "linear-regression", "includes"),
    ("probability", "logistic-regression", "prerequisite"),
    ("linear-algebra", "linear-regression", "prerequisite"),
    ("linear-algebra", "logistic-regression", "prerequisite"),
    ("calculus", "gradient-descent", "prerequisite"),
    ("gradient-descent", "logistic-regression", "prerequisite"),
    ("gradient-descent", "neural-networks", "prerequisite"),
    ("train-test-split", "model-evaluation", "prerequisite"),
    ("model-evaluation", "precision", "includes"),
    ("model-evaluation", "recall", "includes"),
    ("model-evaluation", "confusion-matrix", "includes"),
    ("precision", "f1-score", "prerequisite"),
    ("recall", "f1-score", "prerequisite"),
    ("confusion-matrix", "precision", "prerequisite"),
    ("confusion-matrix", "recall", "prerequisite"),
    ("model-evaluation", "overfitting", "related"),
    ("overfitting", "regularization", "related"),
    ("overfitting", "bias-variance", "related"),
    ("underfitting", "bias-variance", "related"),
    ("train-test-split", "cross-validation", "prerequisite"),
    ("decision-trees", "random-forest", "prerequisite"),
    ("feature-engineering", "logistic-regression", "related"),
    ("supervised-learning", "model-evaluation", "related"),
]
